#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find $TMUX_SEARCH_DIR -mindepth 1 -maxdepth 3 -type d | fzf --layout=reverse --info=inline --border --margin=1 --padding=1 --header="Use CTRL-C to cancel" --preview "ls {}" --color="bg+:-1,fg+:white,spinner:0,hl:yellow,header:blue,info:green,pointer:red,marker:blue,hl+:red")
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]]; then
    if [[ $tmux_running ]] && tmux has-session -t=$selected_name 2> /dev/null; then
        tmux a -t $selected_name
    else
        tmux new-session -s $selected_name -c $selected
    fi
else
    if ! tmux has-session -t=$selected_name 2> /dev/null; then
        tmux new-session -ds $selected_name -c $selected
    fi

    tmux switch-client -t $selected_name
fi

