#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find /mnt/c/Users/nilesh.ugale/work /mnt/d/repos -mindepth 1 -maxdepth 3 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]]; then
    if [[ $tmux_running ]] && tmux has-session -t=$selected_name 2> /dev/null; then
        tmux a -t $selected_name
    else
        tmux new-session -s $selected_name -c $selected
    fi
else
    if ! tmux has-session -t=$selected_name 2> /dev/null; then
        tmux new-session -ds $selected_name -c $selected
    fi

    tmux switch-client -t $selected_name
fi

