#!/bin/bash
# Annotates a task with 'Notes' or 'Notes.*'.

# REQUIRES: awk

# INSTALLATION
# Add this to your ~/.taskrc:
#  alias.addnote=execute /path/to/addnote

# Only add an annotation if we are operating on a single ID
if [ $# -eq 1 ]; then
    desc=$(task $1 info | awk '$0 ~ /^Description/ {print substr($0, index($0,$2))}')
    context=$(task context show | awk '$0 ~ /^Context/ {print}' | awk -F\' '{print $(NF-1)}')
    echo "Attaching to task $1 '$desc'."
#    echo -n "Type a file extension (or none): "
#    read ext
#    ann=""
#    if [ "$ext" != "" ]; then
#        ann="Notes.$ext"
#    else
#        ann="Notes"
#    fi
    ann="$context-notes.norg"
    task $1 annotate -- $ann
    taskopen $1
fi
